name: progparcial2_frontend
description: Frontend Flutter Web para marketplace empresa/cliente
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  provider: ^6.0.5
  flutter_secure_storage: ^8.0.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
